[package]
name = "xmppsocial"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
dotenv = "0.15.0"
feed-rs = "2.1.1"
minidom = "0.16.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
